# Generated by Django 3.0.6 on 2020-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200603_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='english_currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='exchange_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='tenthousand_unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
