# Generated by Django 3.0.6 on 2020-06-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200612_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='max_level',
            field=models.CharField(max_length=50),
        ),
    ]
