# Generated by Django 3.0.6 on 2020-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200617_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
