# Generated by Django 3.0.6 on 2020-06-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0002_auto_20200616_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='content',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='end',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='place',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='position',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='start',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.AddField(
            model_name='company_matchup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AlterField(
            model_name='position',
            name='max_level',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100, null=True)),
                ('user', models.IntegerField(null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Position_item')),
            ],
            options={
                'db_table': 'temps',
            },
        ),
    ]
