# Generated by Django 3.0.6 on 2020-06-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0002_auto_20200604_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='interview',
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=200)),
                ('stock', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('matchup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Matchup')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Position')),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
    ]
