# Generated by Django 3.0.6 on 2020-06-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200603_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
    ]
