# Generated by Django 3.0.6 on 2020-05-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200528_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'expirations',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='positions_item',
            name='expiration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Expiration'),
        ),
    ]
