# Generated by Django 3.0.6 on 2020-06-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='benifit',
            new_name='benefit',
        ),
    ]
