# Generated by Django 3.0.6 on 2020-06-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_proposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
    ]
