# Generated by Django 3.0.6 on 2020-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200528_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions_item',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
