# Generated by Django 3.0.6 on 2020-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200616_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='status',
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='status',
        ),
        migrations.AddField(
            model_name='position_item',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
