# Generated by Django 3.0.6 on 2020-06-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200608_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
