# Generated by Django 3.0.6 on 2020-06-16 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200615_1746'),
        ('company', '0004_auto_20200616_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_matchup',
            name='resume',
        ),
        migrations.AddField(
            model_name='company_matchup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
