# Generated by Django 3.0.6 on 2020-05-31 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_company'),
        ('company', '0005_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position_workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'positions_workplaces',
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'db_table': 'workplaces',
            },
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Companies_matchup',
            new_name='Company_matchup',
        ),
        migrations.RenameModel(
            old_name='Positions_item',
            new_name='Position_item',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='position',
            name='work',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='workplace',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='company.Company'),
        ),
        migrations.AddField(
            model_name='position_workplace',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Position'),
        ),
        migrations.AddField(
            model_name='position_workplace',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Workplace'),
        ),
        migrations.AddField(
            model_name='company',
            name='workplace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplacee', to='company.Workplace'),
        ),
        migrations.AddField(
            model_name='position',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Workplace'),
        ),
    ]
