# Generated by Django 3.0.6 on 2020-06-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200615_1746'),
        ('company', '0005_auto_20200616_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='content',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='end',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='place',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='start',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
