# Generated by Django 3.0.6 on 2020-06-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200531_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='company',
            name='workplace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace', to='company.Workplace'),
        ),
    ]
