# Generated by Django 3.0.6 on 2020-06-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200601_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.City'),
        ),
    ]
