# Generated by Django 3.0.6 on 2020-06-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200615_1746'),
        ('company', '0007_company_matchup_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume'),
        ),
    ]
