# Generated by Django 3.0.6 on 2020-06-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_proposal_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='position',
        ),
    ]
