# Generated by Django 3.0.6 on 2020-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_workplace_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
