# Generated by Django 3.0.6 on 2020-06-01 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200601_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='min_wage',
            new_name='mim_wage',
        ),
    ]
