# Generated by Django 3.0.6 on 2020-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20200601_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='total',
            field=models.CharField(max_length=150),
        ),
    ]
