# Generated by Django 3.0.6 on 2020-06-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200601_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='preferred',
            field=models.TextField(blank=True, null=True),
        ),
    ]
