# Generated by Django 3.0.6 on 2020-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200601_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='workplace',
        ),
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='workplace',
            name='represent',
            field=models.BooleanField(default=0),
        ),
    ]
