# Generated by Django 3.0.6 on 2020-06-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='deleted',
        ),
    ]
