# Generated by Django 3.0.6 on 2020-06-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='browser',
            field=models.CharField(max_length=1000),
        ),
    ]
