# Generated by Django 3.0.6 on 2020-06-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
