# Generated by Django 3.0.6 on 2020-06-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='roles',
            new_name='resume_resume_role',
        ),
    ]
