# Generated by Django 3.0.6 on 2020-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_job_category',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_work',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
