# Generated by Django 3.0.6 on 2020-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialism',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchup',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchup_skill',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_information',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work_information',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
