# Generated by Django 3.0.6 on 2020-06-08 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200608_1808'),
        ('user', '0002_remove_resume_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='role',
        ),
        migrations.AddField(
            model_name='resume',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Job_category'),
        ),
        migrations.CreateModel(
            name='Resume_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Role')),
            ],
            options={
                'db_table': 'resume_roles',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_resume_role',
            field=models.ManyToManyField(related_name='resume_resume_role', through='user.Resume_role', to='company.Role'),
        ),
    ]
