# Generated by Django 3.0.6 on 2020-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200604_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='result',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='result',
            name='description',
        ),
        migrations.RemoveField(
            model_name='result',
            name='email',
        ),
        migrations.RemoveField(
            model_name='result',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='result',
            name='is_matchup',
        ),
        migrations.RemoveField(
            model_name='result',
            name='name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='status',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AlterField(
            model_name='result',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
