# Generated by Django 3.0.6 on 2020-05-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
