# Generated by Django 3.0.6 on 2020-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200615_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='https://s3.ap-northeast-2.amazonaws.com/wanted-public/profile_default.png', max_length=2000),
        ),
    ]
