# Generated by Django 3.0.6 on 2020-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200608_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='school',
        ),
        migrations.AddField(
            model_name='resume',
            name='total_work',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
