# Generated by Django 3.0.6 on 2020-06-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_resume_resume_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_name',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resume_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resume_number',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='resume_title',
            new_name='title',
        ),
    ]
