# Generated by Django 3.0.6 on 2020-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200602_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
