# Generated by Django 3.0.6 on 2020-06-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200603_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='career',
        ),
        migrations.AddField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Resume'),
        ),
    ]
