# Generated by Django 3.0.6 on 2020-06-03 07:06

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200603_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='end',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=partial_date.fields.PartialDateField(null=True),
        ),
    ]
