# Generated by Django 3.0.6 on 2020-06-03 07:09

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200603_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='end',
            field=partial_date.fields.PartialDateField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='start',
            field=partial_date.fields.PartialDateField(null=True),
        ),
    ]
